/**
 * Regenerates src/generated for the RSA SDK. Run after `build`.
 *
 * - errors.ts: every error code, read from the errors files below, with its doc
 *   comment as the message. Fails on a duplicate code.
 * - mbrErrors.ts: MbrManager's codes alone, for mbrManagerSdk.
 * - rsaSha256Verifier.ts: the verifier's bytecode, and the pc of each assert
 *   with an ERR code. A logic signature has no ARC-56 source info, so the SDK
 *   maps a rejection's pc with this. Embedding the bytes means the SDK never
 *   calls algod's compile endpoint, which public nodes don't expose.
 * - RsaSplitConsumerClient.ts: copied from the artifacts.
 */
import { execFileSync } from 'node:child_process'
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const ERROR_FILES = ['src/mbrManager.algo.ts', 'src/rsaErrors.algo.ts', 'smart_contracts/rsa/errors.algo.ts']
const OUT = 'src/generated'
const HEADER = '// Generated by scripts/generate-sdk.mjs. Do not edit.\n\n'

mkdirSync(OUT, { recursive: true })

const errors = {}
const mbrErrors = {}
for (const file of ERROR_FILES) {
  for (const [, message, code] of readFileSync(file, 'utf8').matchAll(/\/\*\*\s*(.+?)\s*\*\/\s*export const \w+ = '([^']+)'/g)) {
    // loggedAssert codes (MbrManager) get their ERR: prefix on chain; plain assert codes carry it.
    const key = code.startsWith('ERR:') ? code : `ERR:${code}`
    if (key in errors) throw new Error(`Duplicate error code ${key} in ${file}`)
    errors[key] = message
    if (file === 'src/mbrManager.algo.ts') mbrErrors[key] = message
  }
}
writeFileSync(`${OUT}/errors.ts`, `${HEADER}export const ErrorMessages: Record<string, string> = ${JSON.stringify(errors, null, 2)}\n`)
writeFileSync(`${OUT}/mbrErrors.ts`, `${HEADER}export const MbrErrorMessages: Record<string, string> = ${JSON.stringify(mbrErrors, null, 2)}\n`)

const tmp = mkdtempSync(join(tmpdir(), 'rsa-sdk-'))
try {
  execFileSync(
    'npx',
    ['puya-ts', 'smart_contracts/rsa/consumer.algo.ts', '--out-dir', tmp, '--output-bytecode', '--output-assembly-report', '--no-output-arc32', '--no-output-arc56', '--no-output-teal', '--no-output-source-map'],
    { stdio: 'ignore' },
  )
  const program = readFileSync(join(tmp, 'RsaSha256Verifier.bin')).toString('base64')
  const report = readFileSync(join(tmp, 'RsaSha256Verifier.assembly-report'), 'utf8')
  const pcs = {}
  for (const [, pc, code] of report.matchAll(/^\|\s*(\d+)\s*\|[^|]*\|\s*(?:assert|err)\s*\/\/\s*(ERR:\S+)/gm)) pcs[pc] = code
  writeFileSync(
    `${OUT}/rsaSha256Verifier.ts`,
    `${HEADER}export const RSA_SHA256_VERIFIER = {\n  program: '${program}',\n  errorPcs: ${JSON.stringify(pcs)} as Record<number, string>,\n}\n`,
  )
} finally {
  rmSync(tmp, { recursive: true, force: true })
}

copyFileSync('smart_contracts/artifacts/rsa/RsaSplitConsumerClient.ts', `${OUT}/RsaSplitConsumerClient.ts`)
console.log(`Generated ${Object.keys(errors).length} error codes and the RSA SDK artifacts in ${OUT}`)
